# Generated by Django 4.1.2 on 2022-10-07 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Park",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("park_code", models.CharField(max_length=10, unique=True)),
                ("park_fullname", models.CharField(default="", max_length=512)),
            ],
        ),
    ]
