# Generated by Django 4.1.2 on 2022-10-08 00:13

from django.db import migrations

def populate_park_ids():
    pass

class Migration(migrations.Migration):

    dependencies = [
        ("park_db", "0001_initial"),
    ]

    operations = []

    
